Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/AndOr:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
    Enabled: false
